pep_config: donaldcampbelljr/human_seqcol_digests:default
output_dir: ${RESULTS}
pipeline_interfaces:
  - pipeline/pipeline_interface.yaml
pipestat:
  pephub_path: donaldcampbelljr/human_seq_col_results:default