pep_config: metadata/pep_config_mus_musculus.yaml
output_dir: ${RESULTS}
pipeline_interfaces:
  - pipeline/pipeline_interface_mm.yaml
pipestat:
  pephub_path: donaldcampbelljr/mouse_seqcol_digests:default
  #flag_file_dir: ${RESULTS}/flags